const data = [
  {
    id: 1,
    title: "Task x",
    dateTime: "9-12-2018",
    creator: "Agusvelaz",
    type: "new",
    priority: "high",
    description: "asdasdgggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg",
  },
  {
    id: 2,
    title: "Task x",
    dateTime: "9-12-2018",
    creator: "pepito",
    type: "new",
    priority: "medium",
    description: "asdasd",
  },
  {
    id: 3,
    title: "Task x",
    dateTime: "9-12-2018",
    creator: "carlitos",
    type: "inProcess",
    priority: "high",
    description: "asdasd",
  },
  {
    id: 4,
    title: "Task x",
    dateTime: "9-12-2018",
    creator: "jorge",
    type: "inProcess",
    priority: "medium",
    description: "asdasd",
  },
  {
    id: 5,
    title: "Task x",
    dateTime: "9-12-2018",
    creator: "Agusvelaz",
    type: "finished",
    priority: "high",
    description: "asdasd",
  },
  {
    id: 6,
    title: "Task x",
    dateTime: "9-12-2018",
    creator: "Agusvelaz",
    type: "finished",
    priority: "medium",
    description: "asdasd",
  },
  {
    id: 7,
    title: "Task x",
    dateTime: "9-12-2018",
    creator: "Agusvelaz",
    type: "new",
    priority: "high",
    description: "asdasd",
  },
];
export default data;
